### ISSUE TITLE
unable to convert yolov4 

### ISSUE THREAD

**Issue by sharoseali** [fumihwh/onnx-pytorch#18]
`(base) sharoze@nova41:~/Downloads/pytorch-YOLOv4-master/onnx-pytorch$ python tutorial.py 
WARNING:root:Cannot get default value for dilations of Conv.
WARNING:root:Cannot get default value for kernel_shape of Conv.
WARNING:root:Cannot get default value for pads of Conv.
WARNING:root:Cannot get default value for strides of Conv.
Traceback (most recent call last):
  File "tutorial.py", line 2, in <module>
    code_gen.gen("yolov4_1_3_416_416_static.onnx", "./")
  File "/home/sharoze/Downloads/pytorch-YOLOv4-master/onnx-pytorch/onnx_pytorch/code_gen.py", line 291, in gen
    model_code_generator.run()
  File "/home/sharoze/Downloads/pytorch-YOLOv4-master/onnx-pytorch/onnx_pytorch/code_gen.py", line 246, in run
    raise NotImplementedError(
NotImplementedError: OpCodeGenerator is unimplemented for Softplus` 
Any suggestion please?

**Comment by fumihwh** [comment]
@sharoseali 
Sorry for late reply. Just need to implement `Softplus`.
Welcome for contribution.
